# Generated by Django 4.0.4 on 2022-06-26 16:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('lastseen', models.DateTimeField(default=datetime.datetime.now, verbose_name='Последний визит')),
                ('devices', models.ManyToManyField(to='vpnDashboard.device', verbose_name='Устройства')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='vpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('creationTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время запуска')),
                ('coordinates', models.CharField(max_length=50, verbose_name='Координаты')),
                ('profiles', models.ManyToManyField(to='vpnDashboard.profile')),
            ],
            options={
                'verbose_name': 'VPN',
                'verbose_name_plural': 'VPNs',
                'ordering': ['-name'],
            },
        ),
    ]
